theme: jekyll-theme-minimal
title: Dj 10053r
description: Alien's training station
baseurl: /
logo: img/100.jpg
mixcloud: https://www.mixcloud.com/jay-dee23/
soundcloud: https://soundcloud.com/10053r
livesets: https://livesets.com/10053r
